name: 'text CI/CD'

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/node@v2
      
      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint

        

    